class Symbols:
    anchor = "⚘"
    arrow_left = "«"
    arrow_right = "»"
    back = "🔙 Kembali"
    bullet = "•"
    check_mark = "✔"
    close = "🗑️"
    cross_mark = "✘"
    diamond_1 = "◇"
    diamond_2 = "◈"
    next = "⤚ Lanjut"
    previous = "Sebelum ⤙"
    radio_select = "◉"
    radio_unselect = "〇"
    triangle_left = "◂"
    triangle_right = "▸"
